server:
  port: 9090
  servlet:
    context-path: /stscode
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: Reset123
    url: jdbc:mysql://localhost:3306/stsdemodb
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57InnoDBDialect
        format_sql: true
    show-sql: true
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
